monero-wallet-cli.md: `address all` instead of `... list`
There appears to be no such command as `address list`. When I run it I get: 
```
Error: usage: address [ new <label text with white spaces allowed> | all | <index_min> [<index_max>] | label <index> <label text with white spaces allowed> | device [<index>] | one-off <account> <subaddress>]
```